Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using NETTEST2.Models;
using Microsoft.AspNet.Identity.Owin;

namespace NETTEST2.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : BaseController
    {

        public ActionResult Index()
        {
            using (IdentityDbContext context = new IdentityDbContext())
            {
                var roles = context.Roles.ToList();
                return View(roles);
            }
        }
        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                IdentityDbContext context = new IdentityDbContext();
                context.Roles.Add(new Microsoft.AspNet.Identity.EntityFramework.IdentityRole()
                {
                    Name = collection["RoleName"]
                });
                context.SaveChanges();
                ViewBag.ResultMessage = "Role created successfully !";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Delete(string RoleName)
        {
            IdentityDbContext context = new IdentityDbContext();
            var thisRole = context.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            context.Roles.Remove(thisRole);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET: /Roles/Edit/5
        public ActionResult Edit(string roleName)
        {
            IdentityDbContext context = new IdentityDbContext();
            var thisRole = context.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            return View(thisRole);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Microsoft.AspNet.Identity.EntityFramework.IdentityRole role)
        {
            try
            {
                IdentityDbContext context = new IdentityDbContext();
                context.Entry(role).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ManageUserRoles()
        {
            IdentityDbContext context = new IdentityDbContext();
            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr =>

            new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RoleAddToUser(string UserName, string RoleName)
        {
            IdentityDbContext context = new IdentityDbContext();
            ApplicationUser user = new ApplicationUser();
            user = UserManager.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            UserManager.AddToRole(user.Id, RoleName);

            ViewBag.ResultMessage = "Role created successfully !";

            // prepopulat roles for the view dropdown
            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;

            return View("ManageUserRoles");
        }
        public ActionResult MoneyAddToUser()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MoneyAddToUser(string UserNameU, string MoneyAmount)
        {
            ApplicationUser user = new ApplicationUser();
            user = UserManager.Users.Where(u => u.UserName.Equals(UserNameU, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            if(MoneyAmount.Length==0)
            {
                ViewBag.Money = user.Money;
            }
            else
            {
                user.Money = Convert.ToDecimal(MoneyAmount, System.Globalization.CultureInfo.InvariantCulture);
                UserManager.Update(user);
                ViewBag.Money = user.Money;
            }
            return View("MoneyAddToUser");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetRoles(string UserName)
        {
            if (!string.IsNullOrWhiteSpace(UserName))
            {
                IdentityDbContext context = new IdentityDbContext();
                ApplicationUser user = new ApplicationUser();
                user = UserManager.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

                ViewBag.RolesForThisUser = UserManager.GetRoles(user.Id);

                // prepopulat roles for the view dropdown
                var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
                ViewBag.Roles = list;
            }

            return View("ManageUserRoles");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRoleForUser(string UserName, string RoleName)
        {
            IdentityDbContext context = new IdentityDbContext();
            ApplicationUser user = new ApplicationUser();
            user = UserManager.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            if (UserManager.IsInRole(user.Id, RoleName))
            {
                UserManager.RemoveFromRole(user.Id, RoleName);
                ViewBag.ResultMessage = "Role removed from this user successfully !";
            }
            else
            {
                ViewBag.ResultMessage = "This user doesn't belong to selected role.";
            }
            // prepopulat roles for the view dropdown
            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;

            return View("ManageUserRoles");
        }
    }
}

Controllers/TestController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NETTEST2.Models.Offers;
using NETTEST2.Models.Cars;
using NETTEST2.Models.Context;
using NETTEST2.Models.CarViewModel;
using NETTEST2.Models;
using System.IO;
using System.Diagnostics;

namespace NETTEST2.Controllers
{
    public class TestController : BaseController
    {

        // GET: User
        [Route("User")]
        public async Task<ActionResult> ShowAsync(Models.UserPage model)
        {
            var userData = await this.UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (userData == null)
            {
                return View("Error");
            }
            model.Email = userData.Email;
            model.Id = userData.Id;
            model.PasswordHash = userData.PasswordHash;
            model.UserName = userData.UserName;
            model.Money = userData.Money;
            model.ImageModelUsers = userData.ImageModelsUser;
            model.UserAuth = true;
            model.Offers = userData.Offers;

            if (!ModelState.IsValid)
            {
                return new EmptyResult();
            }

            return View(model);
        }

        // GET: User
        [Route("User/{id}")]
        public async Task<ActionResult> ShowAsync(Models.UserPage model, string id)
        {
            var userData = await this.UserManager.FindByIdAsync(id);
            if (userData == null)
            {
                return View("Error");
            }

            model.Email         = userData.Email;
            model.Id            = userData.Id;
            model.PasswordHash  = userData.PasswordHash;
            model.UserName      = userData.UserName;
            model.Money         = userData.Money;
            model.ImageModelUsers = userData.ImageModelsUser;
            model.UserAuth = false;
            model.Offers = userData.Offers;

            if (!ModelState.IsValid)
            {
                return new EmptyResult();
            }

            if (userData.Id == User.Identity.GetUserId())
            {
                model.UserAuth = true;
            }

            return View(model);
        }
     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemoveUser(string userid)
        {
            bool iLikeCookies = false;
            if (userid == User.Identity.GetUserId())
                iLikeCookies = true;
            var user = await UserManager.FindByIdAsync(userid);
            await UserManager.DeleteAsync(user);
            if(iLikeCookies)
            HttpContext.GetOwinContext().Authentication.SignOut(DefaultAuthenticationTypes.ApplicationCookie);

            return RedirectToAction("ShowAll", "User");
        }

        [Route("Admin/All")]
        [Authorize(Roles = "Admin")]
        public ActionResult ShowAll()
        {
            var modelList = new List<Models.UserPage>();
            var userDataList = UserManager.Users.ToList();
            if (userDataList == null)
            {
                return View("Error");
            }
            foreach (var userData in userDataList)
            {

                modelList.Add(new Models.UserPage()
                {
                    Email = userData.Email,
                    Id = userData.Id,
                    PasswordHash = userData.PasswordHash,
                    UserName = userData.UserName,
                    Money = userData.Money
                });
            }
            if (!ModelState.IsValid)
            {
                return new EmptyResult();
            }

            return View(modelList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddPhoto(ImageModelUser model)
        {
            model.ImageFile = Request.Files["ImageFile"];
            string fileName = Path.GetFileNameWithoutExtension(model.ImageFile.FileName.ToString());
            string extension = Path.GetExtension(model.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            model.ImagePath = "~/Images/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
            model.ImageFile.SaveAs(fileName);
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            user.ImageModelsUser.Add(model);
            await UserManager.UpdateAsync(user);
            return Redirect(Request.UrlReferrer.ToString());
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateOffer(CarView view)
        {
            ImageModel model = new ImageModel();
            model.ImageFile= Request.Files["ImageFile"];
            string fileName = Path.GetFileNameWithoutExtension(model.ImageFile.FileName.ToString());
            string extension = Path.GetExtension(model.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            model.ImagePath = "~/Images/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
            model.ImageFile.SaveAs(fileName);
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            var details = new CarDetails()
            {
                AccelTime = Convert.ToDecimal(view.accel, System.Globalization.CultureInfo.InvariantCulture),
                CarType=view.cartype,
                CurbWeight= Convert.ToDecimal(view.curb, System.Globalization.CultureInfo.InvariantCulture),
                DriveType=view.drive,
                EngineType=view.engine,
                GasMileage= Convert.ToDecimal(view.gas, System.Globalization.CultureInfo.InvariantCulture),
                GearboxType=view.gear,
                Power= Convert.ToInt32(view.power),
                Price=Convert.ToDecimal(view.price, System.Globalization.CultureInfo.InvariantCulture),
                TopSpeed= Convert.ToInt32(view.top),
                Torque= Convert.ToInt32(view.torque)
            };

            var imagesList = new List<ImageModel>();
            imagesList.Add(model);
            var carList = new List<Car>();

            var car = new Car() 
            {
                Brand = view.brand,
                Model = view.model,
                YearOfManufacture = Convert.ToInt32(view.yom),
                CarDetails = details,
                ImageModels = imagesList
            };
            carList.Add(car);
            var offer = new Offer()
            {
                Name = view.name,
                Price = Convert.ToDecimal(view.price, System.Globalization.CultureInfo.InvariantCulture),
                Cars = carList
            };
            user.Offers.Add(offer);
            await UserManager.UpdateAsync(user);
            return Redirect(Request.UrlReferrer.ToString());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemoveOffer(string userid,int indexid)
        {
            var user = await UserManager.FindByIdAsync(userid);
            var element = user.Offers.Where(e => e.OfferID == indexid).FirstOrDefault();
            user.Offers.Remove(element);
            await UserManager.UpdateAsync(user);
            return Redirect(Request.UrlReferrer.ToString());
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BuyOffer(string userid, int indexid)
        {
            var buyer = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            var seller = await UserManager.FindByIdAsync(userid);
            var offer = seller.Offers.Where(e => e.OfferID == indexid).FirstOrDefault();
            if (buyer.Money >= offer.Price)
            {
                seller.Money += offer.Price;
                buyer.Money -= offer.Price;
                seller.Offers.Remove(offer);
                buyer.Offers.Add(offer);
                await UserManager.UpdateAsync(seller);
                await UserManager.UpdateAsync(buyer);
            }
            return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="body-dark">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nazwa aplikacji", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Strona główna", "Index", "Home")</li>
                    <li>@Html.ActionLink("Informacje", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Profil", "ShowAsync", "Test")</li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Admin", "ShowAll", "Test")</li>
                        <li>@Html.ActionLink("Role", "ManageUserRoles", "Roles")</li>
                        <li>@Html.ActionLink("Środki", "MoneyAddToUser", "Roles")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Moja aplikacja ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_OfferboxPartial.cshtml
@{ 
    var item = ViewBag.item;
    var UserAuth = ViewBag.UserAuth;
}
<div class="container-fluid">
    <div class="row">
        <img src="@Url.Content(item.Cars.ToArray()[0].ImageModels.ToArray()[0].ImagePath)" class="img-responsive roundedUP" />
        <div class="offerbox text-center">
            <div class="avtr">
                @if (item.ApplicationUser.ImageModelsUser == null || item.ApplicationUser.ImageModelsUser.Count == 0)
                {
                    <img src="@Url.Content("~/Images/avatar.jpg")" class="img-responsive img-avtr" />
                }
                else
                {
                    <img src="@Url.Content(item.ApplicationUser.ImageModelsUser.ToArray()[item.ApplicationUser.ImageModelsUser.Count - 1].ImagePath)" class="img-responsive img-avtr" />
                }
                @{var a = Request.Url.GetLeftPart(UriPartial.Authority) + Url.Content("~") + "User/" + item.ApplicationUserId; }
                <b style="font-size:18px; margin-left:5px;"><a href="@a"> @item.ApplicationUser.UserName</a></b>
            </div>
            <br /><br />
            <h1><b>@item.Name</b></h1>
            <hr />
            <table style="width:100%; display:inline-table;" class="table-condensed">
                <tr>
                    <td><b>Price<br /></b>@item.Price $</td>
                    <td><b>Brand<br /></b>@item.Cars.ToArray()[0].Brand</td>
                    <td><b>Model<br /></b>@item.Cars.ToArray()[0].Model</td>
                </tr>
                <tr>
                    <td><b>Year<br /></b>@item.Cars.ToArray()[0].YearOfManufacture</td>
                    <td><b>Acceleration<br /></b>@item.Cars.ToArray()[0].CarDetails.AccelTime s</td>
                    <td><b>Car Type<br /></b>@item.Cars.ToArray()[0].CarDetails.CarType</td>
                </tr>
                <tr>
                    <td><b>Weight<br /></b>@item.Cars.ToArray()[0].CarDetails.CurbWeight kg</td>
                    <td><b>Drive Type<br /></b>@item.Cars.ToArray()[0].CarDetails.DriveType</td>
                    <td><b>Engine Type<br /></b>@item.Cars.ToArray()[0].CarDetails.EngineType</td>
                </tr>
                <tr>
                    <td><b>Gas Mileage<br /></b>@item.Cars.ToArray()[0].CarDetails.GasMileage l/100 km</td>
                    <td><b>Gearbox Type<br /></b>@item.Cars.ToArray()[0].CarDetails.GearboxType</td>
                    <td><b>Power<br /></b>@item.Cars.ToArray()[0].CarDetails.Power bhp</td>

                </tr>
                <tr>
                    <td><b>Top Speed<br /></b>@item.Cars.ToArray()[0].CarDetails.TopSpeed kph</td>
                    <td><b>Torque<br /></b>@item.Cars.ToArray()[0].CarDetails.Torque Nm</td>
                </tr>
            </table>
            @if (UserAuth || User.IsInRole("Admin") || User.IsInRole("Moderator"))
            {
                <form action="Test/RemoveOffer" method="post" class="btn-default" id="@item.OfferID removeOfferForm" style="display:inline;">
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="userid" name="userid" value="@item.ApplicationUserId" />
                    <input type="hidden" id="indexid" name="indexid" value="@item.OfferID" />
                    <a class="btn btn-default" href="javascript:document.getElementById('@item.OfferID removeOfferForm').submit()">Usuń Oferte</a>
                </form>
            }
            @if (!UserAuth && User.Identity.IsAuthenticated)
            {
                <form action="Test/BuyOffer" method="post" class="btn-default" id="@item.OfferID buyOfferForm" style="display:inline;">
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="userid" name="userid" value="@item.ApplicationUserId" />
                    <input type="hidden" id="indexid" name="indexid" value="@item.OfferID" />
                    <a class="btn btn-default" href="javascript:document.getElementById('@item.OfferID buyOfferForm').submit()">Kup Oferte</a>
                </form>
            }
        </div>
    </div>
</div>